[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.146.0"
  GO_VERSION = "1.23.4"
  TZ = "Asia/Shanghai"

[context.production.environment]
  HUGO_ENV = "production"
